CREATE DATABASE PLC_1211C;

CREATE USER 'Scada_Server'@'192.168.28.3' IDENTIFIED BY '000000';

GRANT ALL PRIVILEGES ON PLC_1211C.* TO 'Scada_Server'@'localhost';

FLUSH PRIVILEGES;

USE PLC_1211C;
CREATE TABLE Digital_Input (
    ID TINYINT PRIMARY KEY,
    Input_Name VARCHAR(50) NOT NULL,
    Value TINYINT (1)
);
CREATE TABLE Digital_Output (
    ID TINYINT PRIMARY KEY,
    Output_Name VARCHAR(50) NOT NULL,
    Value TINYINT (1)
);
CREATE TABLE  Analog_Input (
    ID TINYINT PRIMARY KEY,
    Input_Name VARCHAR(50) NOT NULL,
    Value FLOAT
);